### PR TITLE
Ensure that defaults in Tale creation follow the schema

### PR DESCRIPTION
**Pull request by Xarthisius**
### How to test

1. Using swagger page create a Tale with "authors" missing or set to `None`  (same with e.g. "public" set to `None`)
1. You should get a valid Tale. Before you'd get a Tale with `authors: "Firstname Lastname"` or `public: None` which would break schema internally.

### CODE REVIEW

**Comment by ThomasThelen** [comment]
My default Tale comes back with
```
"authors": [
   "orcid",
   "firstName",
   "lastName"
],
```
which is problematic if you try to update it since it's expecting
```json
[
   {
      "firstName": "",
      "etc": ""
   },
   {
      "firstName": "",
      "etc": ""
   }
]
```
I think the change should be
```python
default_authors = list()
default_authors.append(dict(firstName=user["firstName"], lastName=user["lastName"], orcid=""))
```
I tested that change and got what I think the expected structure is back,

```
"authors": [
   {
      "firstName": "Carl",
      "lastName": "Ford",
      "orcid": ""
   }
 ]
```

**Comment by Xarthisius** [comment]
@ThomasThelen I applied slightly different fix. It should be good now. Thanks for catching this!

**Comment by ThomasThelen** [comment]
Was there a flake8 change? That's quite a few failures. If you want to handle them in this issue, I can take the publishing, data importers, util, and exporting related failures if you want to take the rest, task, schema, and models.

Otherwise I tested with the latest commit and it looks fine to me.

**Comment by craig-willis** [comment]
I really like tale creation adding me as an author by default, but the ORCID is empty and non-editable. Doesn't this cause problems with the export?  I know we don't validate ORCIDs on input, but I thought a blank ORCID would cause a problem during export or publish.

**Comment by ThomasThelen** [comment]
Tested and looks great. Can confirm @craig-willis's point above; are there any strong opinions about defaulting the ORCID to an empty string? Previously, one could create a Tale and export it immediately but now the user has to add the ORCID to the author field beforehand.

**Comment by ThomasThelen** [comment]
Setting the default ORCID to `https://orcid.org/0000-0000-0000-0000` lets users export their Tales without having to manually add their ORCID (tested this).
If we don't want to default the ORCID, then I think this PR is ready to be merged.

**Comment by ThomasThelen** [comment]
After the discussion on the 19 Oct. 202 call we decided on how to handle the ORCID. See [this](https://github.com/whole-tale/girder_wholetale/issues/432) issue for more information. We decided that this pull request should be fine to merge.

**Review by ThomasThelen — APPROVED** [review]

**Pull request merged**
