### PR TITLE
[WIP] Publishers config

### PR DESCRIPTION
**Pull request by Xarthisius**
Provide a list of places where we can publish tales as a config option.

### CODE REVIEW

**Comment by ThomasThelen** [comment]
Is there any opposition to adding a flag [here](https://github.com/whole-tale/girder_wholetale/pull/303/files#diff-6d45fc384e824adbffc8d18ad2c6dabeR36) to represent a development/production node? This would allow filtering in other places (such as the dashboard)

**Comment by Xarthisius** [comment]
> Is there any opposition to adding a flag [here](https://github.com/whole-tale/girder_wholetale/pull/303/files#diff-6d45fc384e824adbffc8d18ad2c6dabeR36) to represent a development/production node? This would allow filtering in other places (such as the dashboard)

I just copy'n'pasted the mapping from your dashboard PR. I thought we're using explicit CN url rather than a flag now.

**Comment by ThomasThelen** [comment]
At the bottom of the PR there was a discussion to only show the dev repository when on dashboard.dev, so I don't hold you to any of that. I can do this by checking the dashboard's config.dev flag, but would still need to have a string for the CN to check against, which might get messy if we restrict more repositories.
```
if (config.dev) {
   // only show dev node
  repositories.forEach ( repository => {
    if (repository.coordinatingNode === 'cn-stage2.etc) {
      displayRepositories.append(repository)
    }
   })
}
```

If we had a flag on the repository itself we could just check the flag instead.

**Comment by Xarthisius** [comment]
I think that won't be necessary. We're gonna have a dev instance by default, and on prod we will set the dropdown to proper values via custom config.

**Pull request closed without merging**
